name: Build and push texlive-music-devcontainer images

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          imageTag: lilypond-${{ github.ref_name }}
          subFolder: lilypond
          push: always